# ------------------------------------------------------------------------------------
# <copyright company="Aspose Pty Ltd" file="groupdocs_conversion_cloud.rb">
#   Copyright (c) 2003-2019 Aspose Pty Ltd
# </copyright>
# <summary>
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.
# </summary>
# ------------------------------------------------------------------------------------

# Common files
require_relative 'groupdocs_conversion_cloud/api_client'
require_relative 'groupdocs_conversion_cloud/api_error'
require_relative 'groupdocs_conversion_cloud/version'
require_relative 'groupdocs_conversion_cloud/configuration'

# Models
require_relative 'groupdocs_conversion_cloud/models/convert_options'
require_relative 'groupdocs_conversion_cloud/models/convert_settings'
require_relative 'groupdocs_conversion_cloud/models/disc_usage'
require_relative 'groupdocs_conversion_cloud/models/error'
require_relative 'groupdocs_conversion_cloud/models/error_details'
require_relative 'groupdocs_conversion_cloud/models/file_versions'
require_relative 'groupdocs_conversion_cloud/models/files_list'
require_relative 'groupdocs_conversion_cloud/models/files_upload_result'
require_relative 'groupdocs_conversion_cloud/models/load_options'
require_relative 'groupdocs_conversion_cloud/models/object_exist'
require_relative 'groupdocs_conversion_cloud/models/storage_exist'
require_relative 'groupdocs_conversion_cloud/models/storage_file'
require_relative 'groupdocs_conversion_cloud/models/stored_converted_result'
require_relative 'groupdocs_conversion_cloud/models/supported_format'
require_relative 'groupdocs_conversion_cloud/models/watermark_options'
require_relative 'groupdocs_conversion_cloud/models/cad_load_options'
require_relative 'groupdocs_conversion_cloud/models/csv_load_options'
require_relative 'groupdocs_conversion_cloud/models/diagram_load_options'
require_relative 'groupdocs_conversion_cloud/models/email_load_options'
require_relative 'groupdocs_conversion_cloud/models/file_version'
require_relative 'groupdocs_conversion_cloud/models/html_convert_options'
require_relative 'groupdocs_conversion_cloud/models/image_convert_options'
require_relative 'groupdocs_conversion_cloud/models/image_load_options'
require_relative 'groupdocs_conversion_cloud/models/one_load_options'
require_relative 'groupdocs_conversion_cloud/models/pdf_convert_options'
require_relative 'groupdocs_conversion_cloud/models/pdf_load_options'
require_relative 'groupdocs_conversion_cloud/models/presentation_convert_options'
require_relative 'groupdocs_conversion_cloud/models/presentation_load_options'
require_relative 'groupdocs_conversion_cloud/models/spreadsheet_convert_options'
require_relative 'groupdocs_conversion_cloud/models/spreadsheet_load_options'
require_relative 'groupdocs_conversion_cloud/models/svg_convert_options'
require_relative 'groupdocs_conversion_cloud/models/txt_convert_options'
require_relative 'groupdocs_conversion_cloud/models/txt_load_options'
require_relative 'groupdocs_conversion_cloud/models/word_processing_convert_options'
require_relative 'groupdocs_conversion_cloud/models/word_processing_load_options'
require_relative 'groupdocs_conversion_cloud/models/xml_load_options'
require_relative 'groupdocs_conversion_cloud/models/xps_convert_options'
require_relative 'groupdocs_conversion_cloud/models/bmp_convert_options'
require_relative 'groupdocs_conversion_cloud/models/bmp_load_options'
require_relative 'groupdocs_conversion_cloud/models/cgm_convert_options'
require_relative 'groupdocs_conversion_cloud/models/dcm_convert_options'
require_relative 'groupdocs_conversion_cloud/models/dcm_load_options'
require_relative 'groupdocs_conversion_cloud/models/dgn_load_options'
require_relative 'groupdocs_conversion_cloud/models/djvu_convert_options'
require_relative 'groupdocs_conversion_cloud/models/dng_convert_options'
require_relative 'groupdocs_conversion_cloud/models/dng_load_options'
require_relative 'groupdocs_conversion_cloud/models/doc_convert_options'
require_relative 'groupdocs_conversion_cloud/models/doc_load_options'
require_relative 'groupdocs_conversion_cloud/models/docm_convert_options'
require_relative 'groupdocs_conversion_cloud/models/docm_load_options'
require_relative 'groupdocs_conversion_cloud/models/docx_convert_options'
require_relative 'groupdocs_conversion_cloud/models/docx_load_options'
require_relative 'groupdocs_conversion_cloud/models/dot_convert_options'
require_relative 'groupdocs_conversion_cloud/models/dot_load_options'
require_relative 'groupdocs_conversion_cloud/models/dotm_convert_options'
require_relative 'groupdocs_conversion_cloud/models/dotm_load_options'
require_relative 'groupdocs_conversion_cloud/models/dotx_convert_options'
require_relative 'groupdocs_conversion_cloud/models/dotx_load_options'
require_relative 'groupdocs_conversion_cloud/models/dwf_load_options'
require_relative 'groupdocs_conversion_cloud/models/dwg_load_options'
require_relative 'groupdocs_conversion_cloud/models/dxf_load_options'
require_relative 'groupdocs_conversion_cloud/models/emf_convert_options'
require_relative 'groupdocs_conversion_cloud/models/emf_load_options'
require_relative 'groupdocs_conversion_cloud/models/eml_load_options'
require_relative 'groupdocs_conversion_cloud/models/emlx_load_options'
require_relative 'groupdocs_conversion_cloud/models/epub_convert_options'
require_relative 'groupdocs_conversion_cloud/models/gif_convert_options'
require_relative 'groupdocs_conversion_cloud/models/gif_load_options'
require_relative 'groupdocs_conversion_cloud/models/ico_convert_options'
require_relative 'groupdocs_conversion_cloud/models/ico_load_options'
require_relative 'groupdocs_conversion_cloud/models/ifc_load_options'
require_relative 'groupdocs_conversion_cloud/models/igs_load_options'
require_relative 'groupdocs_conversion_cloud/models/j2c_load_options'
require_relative 'groupdocs_conversion_cloud/models/j2k_load_options'
require_relative 'groupdocs_conversion_cloud/models/jp2_load_options'
require_relative 'groupdocs_conversion_cloud/models/jpeg_load_options'
require_relative 'groupdocs_conversion_cloud/models/jpf_load_options'
require_relative 'groupdocs_conversion_cloud/models/jpg_convert_options'
require_relative 'groupdocs_conversion_cloud/models/jpg_load_options'
require_relative 'groupdocs_conversion_cloud/models/jpm_load_options'
require_relative 'groupdocs_conversion_cloud/models/jpx_load_options'
require_relative 'groupdocs_conversion_cloud/models/mht_load_options'
require_relative 'groupdocs_conversion_cloud/models/mobi_load_options'
require_relative 'groupdocs_conversion_cloud/models/msg_load_options'
require_relative 'groupdocs_conversion_cloud/models/odg_convert_options'
require_relative 'groupdocs_conversion_cloud/models/odg_load_options'
require_relative 'groupdocs_conversion_cloud/models/odp_convert_options'
require_relative 'groupdocs_conversion_cloud/models/odp_load_options'
require_relative 'groupdocs_conversion_cloud/models/ods_convert_options'
require_relative 'groupdocs_conversion_cloud/models/ods_load_options'
require_relative 'groupdocs_conversion_cloud/models/odt_convert_options'
require_relative 'groupdocs_conversion_cloud/models/odt_load_options'
require_relative 'groupdocs_conversion_cloud/models/ost_load_options'
require_relative 'groupdocs_conversion_cloud/models/otp_convert_options'
require_relative 'groupdocs_conversion_cloud/models/otp_load_options'
require_relative 'groupdocs_conversion_cloud/models/ots_convert_options'
require_relative 'groupdocs_conversion_cloud/models/ots_load_options'
require_relative 'groupdocs_conversion_cloud/models/ott_convert_options'
require_relative 'groupdocs_conversion_cloud/models/ott_load_options'
require_relative 'groupdocs_conversion_cloud/models/plt_load_options'
require_relative 'groupdocs_conversion_cloud/models/png_convert_options'
require_relative 'groupdocs_conversion_cloud/models/png_load_options'
require_relative 'groupdocs_conversion_cloud/models/potm_convert_options'
require_relative 'groupdocs_conversion_cloud/models/potm_load_options'
require_relative 'groupdocs_conversion_cloud/models/potx_convert_options'
require_relative 'groupdocs_conversion_cloud/models/potx_load_options'
require_relative 'groupdocs_conversion_cloud/models/pps_convert_options'
require_relative 'groupdocs_conversion_cloud/models/pps_load_options'
require_relative 'groupdocs_conversion_cloud/models/ppsm_convert_options'
require_relative 'groupdocs_conversion_cloud/models/ppsm_load_options'
require_relative 'groupdocs_conversion_cloud/models/ppsx_convert_options'
require_relative 'groupdocs_conversion_cloud/models/ppsx_load_options'
require_relative 'groupdocs_conversion_cloud/models/ppt_convert_options'
require_relative 'groupdocs_conversion_cloud/models/ppt_load_options'
require_relative 'groupdocs_conversion_cloud/models/pptm_convert_options'
require_relative 'groupdocs_conversion_cloud/models/pptm_load_options'
require_relative 'groupdocs_conversion_cloud/models/pptx_convert_options'
require_relative 'groupdocs_conversion_cloud/models/pptx_load_options'
require_relative 'groupdocs_conversion_cloud/models/psd_convert_options'
require_relative 'groupdocs_conversion_cloud/models/psd_load_options'
require_relative 'groupdocs_conversion_cloud/models/pst_load_options'
require_relative 'groupdocs_conversion_cloud/models/rtf_convert_options'
require_relative 'groupdocs_conversion_cloud/models/stl_load_options'
require_relative 'groupdocs_conversion_cloud/models/tif_load_options'
require_relative 'groupdocs_conversion_cloud/models/tiff_convert_options'
require_relative 'groupdocs_conversion_cloud/models/tiff_load_options'
require_relative 'groupdocs_conversion_cloud/models/tsv_convert_options'
require_relative 'groupdocs_conversion_cloud/models/tsv_load_options'
require_relative 'groupdocs_conversion_cloud/models/vdw_load_options'
require_relative 'groupdocs_conversion_cloud/models/vdx_load_options'
require_relative 'groupdocs_conversion_cloud/models/vsd_load_options'
require_relative 'groupdocs_conversion_cloud/models/vsdm_load_options'
require_relative 'groupdocs_conversion_cloud/models/vsdx_load_options'
require_relative 'groupdocs_conversion_cloud/models/vss_load_options'
require_relative 'groupdocs_conversion_cloud/models/vssm_load_options'
require_relative 'groupdocs_conversion_cloud/models/vssx_load_options'
require_relative 'groupdocs_conversion_cloud/models/vst_load_options'
require_relative 'groupdocs_conversion_cloud/models/vstm_load_options'
require_relative 'groupdocs_conversion_cloud/models/vstx_load_options'
require_relative 'groupdocs_conversion_cloud/models/vsx_load_options'
require_relative 'groupdocs_conversion_cloud/models/vtx_load_options'
require_relative 'groupdocs_conversion_cloud/models/webp_convert_options'
require_relative 'groupdocs_conversion_cloud/models/webp_load_options'
require_relative 'groupdocs_conversion_cloud/models/wmf_convert_options'
require_relative 'groupdocs_conversion_cloud/models/wmf_load_options'
require_relative 'groupdocs_conversion_cloud/models/xls2003_convert_options'
require_relative 'groupdocs_conversion_cloud/models/xls2003_load_options'
require_relative 'groupdocs_conversion_cloud/models/xls_convert_options'
require_relative 'groupdocs_conversion_cloud/models/xls_load_options'
require_relative 'groupdocs_conversion_cloud/models/xlsb_convert_options'
require_relative 'groupdocs_conversion_cloud/models/xlsb_load_options'
require_relative 'groupdocs_conversion_cloud/models/xlsm_convert_options'
require_relative 'groupdocs_conversion_cloud/models/xlsm_load_options'
require_relative 'groupdocs_conversion_cloud/models/xlsx_convert_options'
require_relative 'groupdocs_conversion_cloud/models/xlsx_load_options'
require_relative 'groupdocs_conversion_cloud/models/xltm_convert_options'
require_relative 'groupdocs_conversion_cloud/models/xltm_load_options'
require_relative 'groupdocs_conversion_cloud/models/xltx_convert_options'
require_relative 'groupdocs_conversion_cloud/models/xltx_load_options'
require_relative 'groupdocs_conversion_cloud/models/j2c_convert_options'
require_relative 'groupdocs_conversion_cloud/models/j2k_convert_options'
require_relative 'groupdocs_conversion_cloud/models/jp2_convert_options'
require_relative 'groupdocs_conversion_cloud/models/jpeg_convert_options'
require_relative 'groupdocs_conversion_cloud/models/jpf_convert_options'
require_relative 'groupdocs_conversion_cloud/models/jpm_convert_options'
require_relative 'groupdocs_conversion_cloud/models/jpx_convert_options'
require_relative 'groupdocs_conversion_cloud/models/tif_convert_options'

# APIs
require_relative 'groupdocs_conversion_cloud/api/conversion_api'
require_relative 'groupdocs_conversion_cloud/api/file_api'
require_relative 'groupdocs_conversion_cloud/api/folder_api'
require_relative 'groupdocs_conversion_cloud/api/storage_api'
